apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    app: myapp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/demo"
