apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bootcamp-cluster
  region: us-east-1

iam:
  withOIDC: true

addons: 
- name: vpc-cni 
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest 
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-driver
  version: latest  

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 10