apiVersion: v1 #kubectl api-resources
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-image
    image: mysql
    imagePullPolicy: Always
    ports:
      - containerPort: 3306
        name: db
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: secret
