apiVersion: v1 #kubectl api-resources
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    version: v1
    env: prod
  annotations:
    owner: test
    url: https://google.com
    #kubernetes.io/change-cause: "version 1.0.0"
spec:
  containers:
  - name: nginx-image
    image: nginx:alpine
    imagePullPolicy: Always
