apiVersion: v1
kind: ConfigMap
metadata:
  name: postgress-init-script-configmap
data:
  initdb.sh: |-
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER user_pg WITH PASSWORD 'qwerty';
      CREATE DATABASE demo_db;
      GRANT ALL PRIVILEGES ON DATABASE demo_db TO user_pg;
    EOSQL
