apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-clain
  labels:
    app: postgres
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany
